# Generated by Django 3.0.6 on 2020-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(max_length=200, null=True, verbose_name='著者'),
        ),
    ]
