# Generated by Django 3.0.6 on 2020-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d', verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(max_length=200, null=True, verbose_name='url'),
        ),
    ]
